name: Pipeline principal CI/CD
on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main
jobs:
  test:
    uses: ./.github/workflows/build-test-reutilizable-esclavo.yml
    with:
      java-version: '25'
  deploy-staging:
    needs: test
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout de c贸digo
        uses: actions/checkout@v6.0.2
      - name: Configurar Java 25
        uses: actions/setup-java@v5.2.0
        with:
          distribution: 'temurin'
          java-version: '25'
      - name: Generando ejecutable JAR
        run: mvn clean package -DskipTests
      - name: Deploy a staging
        run: |
          echo "Realizando Deploy a Staging..."
          curl -X POST https://staging.miaplicacion.com/deploy -H "Authorization: Bearer ${{ secrets.STAGING_TOKEN }}"
  deploy-prod:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://pepeapi.com
    steps:
      - name: Checkout de c贸digo
        uses: actions/checkout@v6.0.2
      - name: Configurar Java 25
        uses: actions/setup-java@v5.2.0
        with:
          distribution: 'temurin'
          java-version: '25'
      - name: Generando ejecutable JAR
        run: ./mvnw clean package -DskipTests
      - name: Deploy a Producci贸n
        run: |
          echo "Realizando Deploy a Producci贸n..."
          curl -X POST https://prod.pepeapi.com/deploy -H "Authorization: Bearer ${{ secrets.STAGING_TOKEN }}"
