name: Pipeline principal CI/CD
on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main
jobs:
  test:
    uses: ./.github/workflows/build-test-reutilizable-esclavo.yml
    with:
      java-version: '25'
  deploy-staging:
    needs: test
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout de c贸digo
        uses: actions/checkout@v6.0.2
      - name: Configurar Java 25
        uses: actions/setup-java@v5.2.0
        with:
          distribution: 'temurin'
          java-version: '25'
      - name: Generando ejecutable JAR
        run: mvn clean package -DskipTests
      - name: Deploy a staging
        run: |
          echo "Realizando Deploy a Staging..."
        # curl -X POST https://staging.miaplicacion.com/deploy -H "Authorization: Bearer ${{ secrets.STAGING_TOKEN }}"
  deploy-prod:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    environment:
      name: production
      url: https://pepeapi.com
    steps:
      - name: Checkout de c贸digo
        uses: actions/checkout@v6.0.2
      - name: Configurar Java 25
        uses: actions/setup-java@v5.2.0
        with:
          distribution: 'temurin'
          java-version: '25'
      - name: Generando ejecutable JAR
        run: ./mvnw clean package -DskipTests
      - name: Deploy a Producci贸n
        run: |
          echo "Realizando Deploy a Producci贸n..."
        # curl -X POST https://prod.pepeapi.com/deploy -H "Authorization: Bearer ${{ secrets.STAGING_TOKEN }}"
      - name: Upload de  JAR a workflow artifacts
        uses: actions/upload-artifact@v6.0.0
        with:
          # Artifact name
          name: springboot-app # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: target/*.jar
      - name: Descargando JAR desde workflow artifacts
        uses: actions/download-artifact@v7.0.0
        with: 
          # Name of the artifact to download. If unspecified, all artifacts for the run are downloaded.
          name: springboot-app # optional
      # Agregando assets en un Release
      - uses: comnoco/create-release@v2
        with:
          tag_name: v1.0.0
          release_name: "Release v1.0.0"
          body: "Detalles del release -> Este es un ejemplo de realease que siempre genera el tag v1.0.0"
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
